//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBZPj_Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveRequest
    {
        public int LeaveRequestId { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public string LeaveType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreadedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string UserId { get; set; }
    }
}
