//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBZPj_Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Calendar
    {
        public int CalendarId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LeaveType { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
