//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBZPj_Api.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreadedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string UserId { get; set; }
    }
}
